### Example File for Balena / Deploy all containers

 version: "2"
 services:

 #example to build container out of Repo
  MatrixVisionbase:
    build: 
      context: ./
      dockerfile: ./Dockerfile.template
    network_mode: host
    privileged: true
    restart: always
    expose:
      - 22
    #ports:
    #    # SSH Port 22 mapped to container 22
    #  - 22:22

    #volumes:
    #  #volume on the external storage
    #   - /media/pi/TO\ 1705-913/mvImages:/media